// Generated by CoffeeScript 1.6.3
var MerchantInterface;

MerchantInterface = {
  TransGet: {
    sign: true,
    md5: true,
    secret: true,
    order: ['wmid', 'lmi_payee_purse', 'lmi_payment_no']
  },
  TransRequest: {
    sign: true,
    md5: true,
    secret: true,
    json: true,
    order: ['wmid', 'lmi_payee_purse', 'lmi_payment_no', 'lmi_clientnumber', 'lmi_clientnumber_type']
  },
  TransConfirm: {
    sign: true,
    md5: true,
    secret: true,
    json: true,
    order: ['wmid', 'lmi_payee_purse', 'lmi_wminvoiceid', 'lmi_clientnumber_code']
  },
  TrustRequest: {
    sign: true,
    light: true,
    order: ['wmid', 'lmi_payee_purse', 'lmi_clientnumber', 'lmi_clientnumber_type', 'lmi_sms_type']
  },
  TrustConfirm: {
    sign: true,
    light: true,
    order: ['wmid', 'lmi_purseid', 'lmi_clientnumber_code']
  },
  TransSave: {
    sign: true,
    md5: true,
    secret: true,
    container: 'paymenttags',
    order: ['wmid', 'lmi_payee_purse', 'lmi_payment_no', 'validityperiodinhours']
  }
};

module.exports = MerchantInterface;
