// Generated by CoffeeScript 1.6.3
var BaseService, MerchantEnvelope1, MerchantEnvelope2, MerchantService, Signer,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BaseService = require('./base');

Signer = require('../signer');

MerchantEnvelope1 = (function() {
  function MerchantEnvelope1() {}

  MerchantEnvelope1.CLASSIC_HOST = 'merchant.webmoney.ru';

  MerchantEnvelope1.LIGHT_HOST = 'merchant.wmtransfer.com';

  MerchantEnvelope1.prototype._prepare = function(options) {
    var content;
    content = {
      wmid: this.wmid
    };
    extend(content, options.data);
    content.sign = '12345';
    return {
      'merchant.request': content
    };
  };

  return MerchantEnvelope1;

})();

MerchantEnvelope2 = (function() {
  function MerchantEnvelope2() {}

  MerchantEnvelope2.DEFAULT_HOST = 'merchant.webmoney.ru';

  MerchantEnvelope2.prototype._prepare = function(options) {
    var content;
    content = {
      signtags: {
        wmid: this.wmid
      }
    };
    content[options.container] = options.data;
    content.signtags.sign = '12345';
    return {
      'merchant.request': content
    };
  };

  return MerchantEnvelope2;

})();

MerchantService = (function(_super) {
  __extends(MerchantService, _super);

  function MerchantService(host, port) {
    MerchantService.__super__.constructor.call(this, host, port);
  }

  MerchantService.prototype._path = function(options) {
    return '/conf/xml/XML' + options.method + '.asp';
  };

  return MerchantService;

})(BaseService);

module.exports = MerchantService;
