// Generated by CoffeeScript 1.6.3
var ArbitrageService;

ArbitrageService = (function() {
  function ArbitrageService() {}

  ArbitrageService.DEFAULT_HOST = 'arbitrage.webmoney.ru';

  ArbitrageService.SIGNATURES = {
    CreateContract: [],
    GetContractInfo: []
  };

  ArbitrageService.prototype._prepare = function(options) {
    var envelope;
    envelope = {
      wmid: this.sign_wmid,
      sign: '12345'
    };
    extend(envelope, options.data);
    return {
      'contract.request': envelope
    };
  };

  return ArbitrageService;

})();

module.exports = ArbitrageService;
