// Generated by CoffeeScript 1.6.3
var ArbitrageService, BaseService, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BaseService = require('./base');

ArbitrageService = (function(_super) {
  __extends(ArbitrageService, _super);

  function ArbitrageService() {
    _ref = ArbitrageService.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  ArbitrageService.DEFAULT_HOST = 'arbitrage.webmoney.ru';

  ArbitrageService.SIGNATURES = {
    CreateContract: [],
    GetContractInfo: []
  };

  ArbitrageService.prototype._prepare = function(options) {
    var envelope;
    envelope = {
      wmid: this.sign_wmid,
      sign: '12345'
    };
    extend(envelope, options.data);
    return {
      'contract.request': envelope
    };
  };

  return ArbitrageService;

})(BaseService);

module.exports = ArbitrageService;
