// Generated by CoffeeScript 1.6.3
var BaseService, XML, https, iconv;

https = require('https');

iconv = require('iconv-lite');

XML = require('xml-objects').XML;

BaseService = (function() {
  function BaseService() {}

  BaseService.DEFAULT_PORT = 443;

  return BaseService;

})();

module.exports = BaseService;
