// Generated by CoffeeScript 1.6.3
var MerchantService;

MerchantService = (function() {
  MerchantService.MAIN_HOST = 'merchant.webmoney.ru';

  MerchantService.LIGHT_HOST = 'merchant.wmtransfer.com';

  MerchantService.CONTAINERS = {
    TransGet: {
      sign: true,
      md5: true,
      secret: true
    },
    TransRequest: {
      sign: true,
      md5: true,
      secret: true,
      json: true
    },
    TransConfirm: {
      sign: true,
      md5: true,
      secret: true,
      json: true
    },
    TrustRequest: {
      sign: true,
      light: true
    },
    TrustConfirm: {
      sign: true,
      light: true
    },
    TransSave: {
      sign: true,
      md5: true,
      secret: true
    }
  };

  MerchantService.SIGNATURES = {
    TransGet: ['wmid', 'lmi_payee_purse', 'lmi_payment_no'],
    TransRequest: ['wmid', 'lmi_payee_purse', 'lmi_payment_no', 'lmi_clientnumber', 'lmi_clientnumber_type'],
    TransConfirm: ['wmid', 'lmi_payee_purse', 'lmi_wminvoiceid', 'lmi_clientnumber_code'],
    TrustRequest: ['wmid', 'lmi_payee_purse', 'lmi_clientnumber', 'lmi_clientnumber_type', 'lmi_sms_type'],
    TrustConfirm: ['wmid', 'lmi_purseid', 'lmi_clientnumber_code'],
    TransSave: ['wmid', 'lmi_payee_purse', 'lmi_payment_no', 'validityperiodinhours']
  };

  function MerchantService(host, port, cred) {}

  MerchantService.prototype._path = function(options) {
    return '/conf/xml/XML' + options.method + '.asp';
  };

  MerchantService.prototype._prepare = function(options) {
    var envelope;
    envelope = {
      wmid: this.wmid,
      sign: '12345'
    };
    extend(envelope, options.data);
    return {
      'merchant.request': envelope
    };
  };

  MerchantService.prototype._prepare = function(options) {
    var envelope;
    envelope = {
      signtags: {
        wmid: this.wmid,
        sign: '12345'
      },
      paymenttags: options.data
    };
    return {
      'merchant.request': envelope
    };
  };

  return MerchantService;

})();

module.exports = MerchantService;
