// Generated by CoffeeScript 1.6.3
var PassportService;

PassportService = (function() {
  function PassportService() {}

  PassportService.API_HOST = 'apipassport.webmoney.ru';

  PassportService.PASSPORT_HOST = 'passport.webmoney.ru';

  return PassportService;

})();

module.exports = PassportService;
