// Generated by CoffeeScript 1.6.3
var API_HOST, PASSPORT_HOST, PassportService;

API_HOST = 'apipassport.webmoney.ru';

PASSPORT_HOST = 'passport.webmoney.ru';

PassportService = (function() {
  function PassportService() {}

  return PassportService;

})();

module.exports = PassportService;
