// Generated by CoffeeScript 1.6.3
var BaseService, SIGN_CLASSIC, SIGN_LIGHT, TransferService, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BaseService = require('./base');

SIGN_CLASSIC = 1;

SIGN_LIGHT = 2;

TransferService = (function(_super) {
  __extends(TransferService, _super);

  function TransferService() {
    _ref = TransferService.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  TransferService.DEFAULT_HOST = 'transfer.gdcert.com';

  TransferService.prototype._prepare = function(options) {
    var content;
    content = {
      wmid: this.wmid
    };
    content[options.container] = options.data;
    content.sign = {
      $type: SIGN_CLASSIC,
      $: {
        text: this.signer.digest(this._signString(content, options.order))
      }
    };
    return {
      'w3s.request': content
    };
  };

  return TransferService;

})(BaseService);

module.exports = TransferService;
