// Generated by CoffeeScript 1.6.3
var W3Service;

W3Service = (function() {
  function W3Service() {}

  W3Service.CLASSIC_HOST = 'w3s.webmoney.ru';

  W3Service.LIGHT_HOST = 'w3s.wmtransfer.com';

  W3Service.CONTAINERS = {
    Invoice: 'invoice',
    Trans: 'trans',
    Operations: 'getoperations',
    OutInvoices: 'getoutinvoices',
    FinishProtect: 'finishprotect',
    SendMsg: 'message',
    FindWMPurseNew: 'testwmpurse',
    Purses: 'getpurses',
    InInvoices: 'getininvoices',
    RejectProtect: 'rejectprotect',
    TransMoneyback: 'trans',
    TrustList: 'gettrustlist',
    TrustList2: 'gettrustlist',
    TrustSave2: 'trust',
    CreatePurse: 'createpurse'
  };

  W3Service.SIGNATURES = {
    Invoice: ['invoice.orderid', 'invoice.customerwmid', 'invoice.storepurse', 'invoice.amount', 'invoice.desc', 'invoice.address', 'invoice.period', 'invoice.expiration', 'reqn'],
    Trans: ['reqn', 'trans.tranid', 'trans.pursesrc', 'trans.pursedest', 'trans.amount', 'trans.period', 'trans.pcode', 'trans.desc', 'trans.wminvid'],
    Operations: ['getoperations.purse', 'reqn'],
    OutInvoices: ['getoutinvoices.purse', 'reqn'],
    FinishProtect: ['finishprotect.wmtranid', 'finishprotect.pcode', 'reqn'],
    SendMsg: ['message.receiverwmid', 'reqn', 'message.msgtext', 'message.msgsubj'],
    FindWMPurseNew: ['testwmpurse.wmid', 'testwmpurse.purse'],
    Purses: ['getpurses.wmid', 'reqn'],
    InInvoices: ['getininvoices.wmid', 'getininvoices.wminvid', 'getininvoices.datestart', 'getininvoices.datefinish', 'reqn'],
    RejectProtect: ['rejectprotect.wmtranid', 'reqn'],
    TransMoneyback: ['reqn', 'trans.inwmtranid', 'trans.amount'],
    TrustList: ['gettrustlist.wmid', 'reqn'],
    TrustList2: ['gettrustlist.wmid', 'reqn'],
    TrustSave2: ['wmid', 'trust.purse', 'trust.masterwmid', 'reqn'],
    CreatePurse: ['createpurse.wmid', 'createpurse.pursetype', 'reqn']
  };

  W3Service.prototype._path = function(options) {
    return '/asp/XML' + options.method + '.asp';
  };

  W3Service.prototype._path = function(options) {
    return '/asp/XML' + options.method + 'Cert.asp';
  };

  W3Service.prototype._prepare = function(options) {
    var envelope;
    envelope = {
      reqn: 1,
      wmid: this.wmid,
      sign: '12345'
    };
    envelope['test'] = options.data;
    return {
      'w3s.request': envelope
    };
  };

  W3Service.prototype._prepare = function(options) {
    var envelope;
    envelope = {
      reqn: this.reqn()
    };
    envelope['test'] = options.data;
    return {
      'w3s.request': envelope
    };
  };

  return W3Service;

})();

module.exports = W3Service;
