// Generated by CoffeeScript 1.6.3
var Invoice, InvoiceList, List, OutputInvoice, _ref, _ref1, _ref2,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

List = require('./list');

Invoice = (function(_super) {
  __extends(Invoice, _super);

  function Invoice() {
    _ref = Invoice.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  return Invoice;

})(Payable);

OutputInvoice = (function(_super) {
  __extends(OutputInvoice, _super);

  function OutputInvoice() {
    _ref1 = OutputInvoice.__super__.constructor.apply(this, arguments);
    return _ref1;
  }

  OutputInvoice.prototype.save = function(callback) {
    return this;
  };

  return OutputInvoice;

})(Invoice);

InvoiceList = (function(_super) {
  __extends(InvoiceList, _super);

  function InvoiceList() {
    _ref2 = InvoiceList.__super__.constructor.apply(this, arguments);
    return _ref2;
  }

  InvoiceList.prototype.toArray = function(callback) {
    return this;
  };

  return InvoiceList;

})(List);

module.exports = Invoice;
