// Generated by CoffeeScript 1.6.3
var Document, List, extend;

extend = require('extend');

Document = require('./document');

List = (function() {
  function List(selector) {
    this._selector = selector;
  }

  List.prototype.skip = function(number) {
    return new List();
  };

  List.prototype.limit = function(count) {
    return new List();
  };

  List.prototype.filter = function(selector) {
    return new List();
  };

  List.prototype.invalidate = function() {
    return this;
  };

  return List;

})();

module.exports = List;
