// Generated by CoffeeScript 1.6.3
var Invoice, Message, Payment, Provider;

Payment = require('./payment');

Invoice = require('./invoice');

Message = require('./message');

Provider = (function() {
  function Provider() {}

  Provider.prototype.users = function(wmid) {
    return new UserList(wmid);
  };

  Provider.prototype.createPayment = function(data) {
    return new Payment(data);
  };

  Provider.prototype.createInvoice = function(data) {
    return new Invoice(data);
  };

  Provider.prototype.createMessage = function(data) {
    return new Message(data);
  };

  return Provider;

})();

module.exports = Provider;
