// Generated by CoffeeScript 1.6.3
var Classic, DEFAULT_HOST, DEFAULT_PORT;

DEFAULT_HOST = 'w3s.webmoney.ru';

DEFAULT_PORT = 443;

Classic = (function() {
  function Classic(wmid, key) {
    this.wmid = wmid;
    this.key = key;
  }

  Classic.prototype.prepare = function(options) {
    var envelope;
    envelope = {
      reqn: this.reqn(),
      wmid: this.wmid,
      sign: this.sign()
    };
    envelope[options.name] = options.data;
    return {
      'w3s.request': envelope
    };
  };

  Classic.prototype.path = function(options) {
    return '/asp/XML' + options.name + '.asp';
  };

  return Classic;

})();

module.exports = Classic;
