// Generated by CoffeeScript 1.6.1
var InvoiceList, LazyList,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

LazyList = require('./lazy-list');

InvoiceList = (function(_super) {

  __extends(InvoiceList, _super);

  function InvoiceList() {
    return InvoiceList.__super__.constructor.apply(this, arguments);
  }

  Object.defineProperty(InvoiceList, '__super__', {
    enumerable: false
  });

  InvoiceList.prototype.fetch = function(callback) {
    return this;
  };

  InvoiceList.prototype.pay = function() {
    return this;
  };

  return InvoiceList;

})(LazyList);

module.exports = InvoiceList;
