// Generated by CoffeeScript 1.6.1
var Invoice, Model,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Model = require('./model');

Invoice = (function(_super) {

  __extends(Invoice, _super);

  function Invoice() {
    return Invoice.__super__.constructor.apply(this, arguments);
  }

  Invoice.prototype.save = function(callback) {
    var data;
    data = {
      invoice: {
        amount: this.amount,
        desc: this.description
      }
    };
    this.service.invoke('XMLInvoice', data, callback);
    return this;
  };

  Invoice.prototype.pay = function(callback) {
    var data;
    data = {
      trans: {
        pursesrc: this.source,
        pursedest: this.destination
      }
    };
    this.service.invoke('XMLTrans', data, callback);
    return this;
  };

  return Invoice;

})(Model);

module.exports = Invoice;
