// Generated by CoffeeScript 1.6.3
var CRC_END, CRC_START, EXP_LENGTH_START, FLAG_START, HEADER_SIZE, KEY_DATA_START, Key, LENGTH_START, crypto, fs;

fs = require('fs');

crypto = require('crypto');

HEADER_SIZE = 24;

FLAG_START = 2;

CRC_START = 4;

CRC_END = 20;

LENGTH_START = CRC_END;

EXP_LENGTH_START = 4;

KEY_DATA_START = 2;

Key = (function() {
  var checkData, decryptKeys, parseKeys;

  decryptKeys = function(keys, wmid, password) {
    var digest, index, octet, _i, _len, _ref;
    digest = crypto.createHash('md4').update(wmid).update(password).digest();
    _ref = keys.slice(6);
    for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
      octet = _ref[index];
      keys[index + 6] = octet ^ digest[index % digest.length];
    }
    return void 0;
  };

  checkData = function(header, data) {
    var crc;
    crc = header.toString('hex', CRC_START, CRC_END);
    header.fill(0, FLAG_START, CRC_END);
    return crypto.createHash('md4').update(header).update(data).digest('hex') === crc;
  };

  parseKeys = function(body) {
    var exponent, modulus, offset;
    exponent = new Buffer(body.readUInt16LE(4));
    body.copy(exponent, 0, 4 + KEY_DATA_START, 4 + KEY_DATA_START + exponent.length);
    offset = 4 + KEY_DATA_START + exponent.length;
    modulus = new Buffer(body.readUInt16LE(offset));
    body.copy(modulus, 0, offset + KEY_DATA_START, offset + KEY_DATA_START + modulus.length);
    return new Key(exponent, modulus);
  };

  Key.fromBuffer = function(header, body, wmid, password) {
    decryptKeys(body, wmid, password);
    checkData(header, body);
    return parseKeys(body);
  };

  Key.fromFile = function(fileName, wmid, password) {
    var body, file, header;
    file = fs.openSync(fileName, 'r');
    header = new Buffer(HEADER_SIZE);
    fs.readSync(file, header, 0, header.length);
    body = new Buffer(header.readUInt32LE(LENGTH_START));
    fs.readSync(file, body, 0, body.length);
    fs.closeSync(file);
    return this.fromBuffer(header, body, wmid, password);
  };

  function Key(exponent, modulus) {
    this.exponent = exponent;
    this.modulus = modulus;
  }

  return Key;

})();

module.exports = Key;
