// Generated by CoffeeScript 1.6.1
var LazyList;

LazyList = (function() {

  function LazyList(service) {
    this.service = service;
  }

  LazyList.prototype.filter = function(condition) {
    if (condition != null) {
      this.$filter = condition;
    } else {
      delete this.$filter;
    }
    return this;
  };

  LazyList.prototype.skip = function(count) {
    if (count != null) {
      this.$skip = count;
    } else {
      delete this.$skip;
    }
    return this;
  };

  LazyList.prototype.limit = function(count) {
    if (count != null) {
      this.$limit = count;
    } else {
      delete this.$limit;
    }
    return this;
  };

  LazyList.prototype.fetch = function(callback) {
    callback(new Error('Pure virtual method was called!'));
    return this;
  };

  return LazyList;

})();

module.exports = LazyList;
