// Generated by CoffeeScript 1.6.3
var DEFAULT_HOST, DEFAULT_PORT, Light;

DEFAULT_HOST = 'w3s.wmtransfer.com';

DEFAULT_PORT = 443;

Light = (function() {
  function Light() {}

  Light.prototype.prepare = function(options) {
    var envelope;
    envelope = {
      reqn: this.reqn()
    };
    envelope[options.name] = options.data;
    return {
      'w3s.request': envelope
    };
  };

  Light.prototype.path = function(options) {
    return '/asp/XML' + options.name + 'Cert.asp';
  };

  return Light;

})();

module.exports = Light;
