// Generated by CoffeeScript 1.6.1
var Message, Model,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Model = require('./model');

Message = (function(_super) {

  __extends(Message, _super);

  function Message() {
    return Message.__super__.constructor.apply(this, arguments);
  }

  Message.prototype.send = function(callback) {
    var data;
    data = {
      message: this.data
    };
    this.service.invoke('XMLSendMsg', data, callback);
    return this;
  };

  return Message;

})(Model);

module.exports = Message;
