// Generated by CoffeeScript 1.6.1
var Model;

Model = (function() {

  function Model() {}

  Model.prototype.isNew = function() {
    return this.id == null;
  };

  return Model;

})();

module.exports = Model;
