// Generated by CoffeeScript 1.6.1
var Payment;

Payment = (function() {

  function Payment() {}

  Payment.prototype.process = function(callback) {
    return this;
  };

  return Payment;

})();

module.exports = Payment;
