// Generated by CoffeeScript 1.6.1
var Model, Purse,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Model = require('./model');

Purse = (function(_super) {

  __extends(Purse, _super);

  function Purse() {
    return Purse.__super__.constructor.apply(this, arguments);
  }

  Purse.prototype.save = function(callback) {
    var data;
    data = {
      createpurse: {
        wmid: this.wmid,
        pursetype: 'R',
        desc: this.description
      }
    };
    this.service.invoke('XMLCreatePurse', data, callback);
    return this;
  };

  return Purse;

})(Model);

module.exports = Purse;
