// Generated by CoffeeScript 1.6.1
var InvoiceList, LazyList, OperationList, PurseList,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

LazyList = require('./lazy-list');

OperationList = require('./operation-list');

InvoiceList = require('./invoice-list');

PurseList = (function(_super) {

  __extends(PurseList, _super);

  function PurseList() {
    return PurseList.__super__.constructor.apply(this, arguments);
  }

  Object.defineOwnProperty(PurseList, '__super__', {
    enumerable: false
  });

  PurseList.prototype.fetch = function(callback) {
    return this;
  };

  PurseList.prototype.operations = function() {
    return new OperationList(this.service);
  };

  PurseList.prototype.invoices = function() {
    return new InvoiceList(this.service);
  };

  return PurseList;

})(LazyList);

module.exports = PurseList;
