// Generated by CoffeeScript 1.6.3
var Service, https, iconv;

https = require('https');

iconv = require('iconv-lite');

Service = (function() {
  function Service() {}

  Service.prototype.serialize = function(data) {
    return iconv.encode(XML.stringify(data), 'utf-8');
  };

  Service.prototype.parse = function(data) {
    return XML.parse(iconv.decode(data, 'utf-8'));
  };

  Service.prototype.headers = function(body) {
    return {
      'content-type': 'application/xml; charset=' + this.charset,
      'content-length': body.length
    };
  };

  Service.prototype.invoke = function(options) {
    var body, request;
    body = this.serialize(this.prepare(options.data));
    request = https.request({
      host: this.host,
      port: this.port,
      method: options.method,
      path: this.path(options),
      headers: this.headers(body)
    });
    request.on('response', function(response) {
      var chunks;
      chunks = [];
      response.on('readable', function() {
        chunks.push(response.read());
        return void 0;
      });
      response.on('end', function() {
        var data;
        data = Buffer.concat(chunks);
        if (typeof options.callback === "function") {
          options.callback(null, data);
        }
        return void 0;
      });
      return void 0;
    });
    request.on('error', function(error) {
      if (typeof options.callback === "function") {
        options.callback(error);
      }
      return void 0;
    });
    request.end(body);
    return this;
  };

  return Service;

})();
