// Generated by CoffeeScript 1.6.3
var BigInteger, Signer, crypto;

crypto = require('crypto');

BigInteger = require('biginteger').BigInteger;

Signer = (function() {
  function Signer(key) {
    this.key = key;
  }

  Signer.prototype.digest = function() {
    var hash, random;
    hash = crypto.createHash('md4').update(params.join('')).digest();
    random = crypto.randomBytes(40);
    return console.log(hash, random);
  };

  return Signer;

})();

module.exports = Signer;
