// Generated by CoffeeScript 1.6.3
var BigNum, DEBUG, HASH_START, HEADER_SIZE, RANDOM_SIZE, Signer, crypto;

crypto = require('crypto');

BigNum = require('bignum');

DEBUG = false;

HEADER_SIZE = 2;

HASH_START = HEADER_SIZE;

RANDOM_SIZE = 40;

Signer = (function() {
  function Signer(key) {
    this._exponent = BigNum.fromBuffer(key.exponent, {
      endian: 'little',
      size: 'auto'
    });
    this._modulus = BigNum.fromBuffer(key.modulus, {
      endian: 'little',
      size: 'auto'
    });
  }

  Signer.prototype.digest = function(message) {
    var blob, blobNumber, hash, signNumber;
    hash = crypto.createHash('md4').update(message).digest();
    blob = new Buffer(HEADER_SIZE + hash.length + RANDOM_SIZE);
    blob.writeUInt16LE(blob.length - HEADER_SIZE, 0);
    hash.copy(blob, HASH_START);
    if (!DEBUG) {
      crypto.randomBytes(RANDOM_SIZE).copy(blob, HASH_START + hash.length);
    } else {
      blob.fill(0, HASH_START + hash.length);
    }
    blobNumber = BigNum.fromBuffer(blob, {
      endian: 'little',
      size: 'auto'
    });
    signNumber = blobNumber.powm(this._exponent, this._modulus);
    return Array.prototype.reverse.call(signNumber.toBuffer({
      endian: 'little',
      size: 2
    })).toString('hex');
  };

  return Signer;

})();

module.exports = Signer;
