// Generated by CoffeeScript 1.6.3
var BigNum, DATA_LENGTH_SIZE, DEBUG, HASH_START, RANDOM_SIZE, Signer, crypto;

crypto = require('crypto');

BigNum = require('bignum');

DEBUG = false;

DATA_LENGTH_SIZE = 2;

HASH_START = DATA_LENGTH_SIZE;

RANDOM_SIZE = 40;

Signer = (function() {
  function Signer(key) {
    this._exponent = BigNum.fromBuffer(key.exponent, {
      endian: 'little',
      size: 'auto'
    });
    this._modulus = BigNum.fromBuffer(key.modulus, {
      endian: 'little',
      size: 'auto'
    });
  }

  Signer.prototype.digest = function(message) {
    var blob, blobNumber, hash, random, randomStart, signNumber;
    hash = crypto.createHash('md4').update(message).digest();
    if (!DEBUG) {
      random = crypto.randomBytes(RANDOM_SIZE);
    }
    blob = new Buffer(DATA_LENGTH_SIZE + hash.length + RANDOM_SIZE);
    blob.writeUInt16LE(blob.length - DATA_LENGTH_SIZE, 0);
    hash.copy(blob, HASH_START);
    randomStart = HASH_START + hash.length;
    if (!DEBUG) {
      random.copy(blob, randomStart);
    } else {
      blob.fill(0, randomStart);
    }
    blobNumber = BigNum.fromBuffer(blob, {
      endian: 'little',
      size: 'auto'
    });
    signNumber = blobNumber.powm(this._exponent, this._modulus);
    return Array.prototype.reverse.call(signNumber.toBuffer({
      endian: 'little',
      size: 2
    })).toString('hex');
  };

  return Signer;

})();

module.exports = Signer;
