// Generated by CoffeeScript 1.6.1
var Invoices, Purses, WMID;

Purses = require('./purse-list');

Invoices = require('./invoice-list');

WMID = (function() {

  function WMID(service) {
    this.service = service;
  }

  WMID.prototype.purses = function() {
    return new Purses();
  };

  WMID.prototype.invoices = function() {
    return new Invoices();
  };

  WMID.prototype.passport = function(callback) {
    return this;
  };

  return WMID;

})();

module.exports = WMID;
