// Generated by CoffeeScript 1.6.3
var CODES, W3Interface;

CODES = {
  INTERNAL_ERROR: 4,
  INTERNAL_ERROR: 15,
  INTERNAL_ERROR: 19,
  INTERNAL_ERROR: 23,
  REQN_MUST_BE_GREATER: 102,
  INVALID_SOURCE_WMID: 5,
  INVALID_DESTINATION_WMID: 6,
  INVALID_DESTINATION_PURSE: 7,
  INVALID_SOURCE_PURSE: 11,
  AMOUNT_LE_ZERO: 13,
  INSUFFICIENT_BALANCE: 17,
  INVALID_PCODE: 20,
  PROTECTION_UNSUPPORTED: 22,
  INVALID_INVOICE_ID: 21,
  INVOICE_TIMEOUT: 25,
  DIFFERENT_PURSES_REQUIRED: 26,
  DIFFERENT_PURSE_TYPES: 29,
  DIRECT_PAYMENT_NOT_ALLOWED: 30,
  NO_PAYMENT_AUTH: 35,
  DESTINATION_BALANCE_LIMIT: 58,
  TRANS_ID_EXISTS: 103,
  NOT_ALLOWED: 110,
  NO_TRUST: 111
};

W3Interface = {
  createInvoice: {
    path: 'Invoice',
    request: 'invoice',
    order: ['invoice.orderid', 'invoice.customerwmid', 'invoice.storepurse', 'invoice.amount', 'invoice.desc', 'invoice.address', 'invoice.period', 'invoice.expiration', 'reqn'],
    response: 'invoice'
  },
  outInvoices: {
    path: 'OutInvoices',
    request: 'getoutinvoices',
    order: ['getoutinvoices.purse', 'reqn'],
    response: 'outinvoices'
  },
  inInvoices: {
    path: 'InInvoices',
    request: 'getininvoices',
    order: ['getininvoices.wmid', 'getininvoices.wminvid', 'getininvoices.datestart', 'getininvoices.datefinish', 'reqn'],
    response: 'ininvoices'
  },
  createPayment: {
    path: 'Trans',
    request: 'trans',
    order: ['reqn', 'trans.tranid', 'trans.pursesrc', 'trans.pursedest', 'trans.amount', 'trans.period', 'trans.pcode', 'trans.desc', 'trans.wminvid'],
    response: 'operation'
  },
  operations: {
    path: 'Operations',
    request: 'getoperations',
    order: ['getoperations.purse', 'reqn'],
    response: 'operations'
  },
  finishProtect: {
    path: 'FinishProtect',
    request: 'finishprotect',
    order: ['finishprotect.wmtranid', 'finishprotect.pcode', 'reqn'],
    response: 'operation'
  },
  rejectProtect: {
    path: 'RejectProtect',
    request: 'rejectprotect',
    order: ['rejectprotect.wmtranid', 'reqn'],
    response: 'operation'
  },
  TransMoneyback: {
    path: 'TransMoneyback',
    request: 'trans',
    order: ['reqn', 'trans.inwmtranid', 'trans.amount'],
    response: 'operation'
  },
  createPurse: {
    path: 'CreatePurse',
    request: 'createpurse',
    order: ['createpurse.wmid', 'createpurse.pursetype', 'reqn'],
    response: 'purse'
  },
  purses: {
    path: 'Purses',
    request: 'getpurses',
    order: ['getpurses.wmid', 'reqn'],
    response: 'purses'
  },
  FindWMPurseNew: {
    request: 'testwmpurse',
    order: ['testwmpurse.wmid', 'testwmpurse.purse'],
    response: 'testwmpurse'
  },
  sendMessage: {
    path: 'SendMsg',
    request: 'message',
    order: ['message.receiverwmid', 'reqn', 'message.msgtext', 'message.msgsubj'],
    response: 'message'
  },
  TrustList: {
    request: 'gettrustlist',
    order: ['gettrustlist.wmid', 'reqn'],
    response: 'trustlist'
  },
  TrustList2: {
    request: 'gettrustlist',
    order: ['gettrustlist.wmid', 'reqn'],
    response: 'trustlist'
  },
  TrustSave2: {
    request: 'trust',
    order: ['wmid', 'trust.purse', 'trust.masterwmid', 'reqn'],
    response: 'trust'
  }
};

module.exports = W3Interface;
